FROM mysql:8.0

# Environment variables to initialize the database
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Expose MySQL port
EXPOSE 3306

